[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && gunicorn breathe_esg.wsgi --bind 0.0.0.0:$PORT --workers 2"
healthcheckPath = "/api/auth/token/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
